config/routes.rb
Jcastle2::Application.routes.draw do
  resources :castles
  
  root :to => "home#index"
#  devise_for :users, :controllers => {:registrations => "registrations"}
#  devise_for :users

#  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	devise_for :users, :controllers => {
    registrations: "registrations", 
  #  passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

#  devise_scope :user do 
#  	get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
#  end

  resources :users

  namespace :admin do
  	resources :castles
	end

end

app/models/castle.rb
class Castle < ActiveRecord::Base
end

app/controllers/admin/castles_controller.rb
class Admin::CastlesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_castle, only: [:show, :edit, :update, :destroy]

  def index
    @castles = Castle.all.order(:approved, :castle_name_en)
  end

  def show
  	@castle = Castle.find(params[:id])
  end

  def edit
  	@castle = Castle.find(params[:id])
  end

  # PATCH/PUT /castles/1
  # PATCH/PUT /castles/1.json
  def update
    respond_to do |format|
      if @castle.update(castle_params)
        format.html { redirect_to admin_castle_path(@castle), notice: 'Castle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @castle.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_castle
      @castle = Castle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def castle_params
      params.require(:castle).permit!
    end

end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController
  before_action :set_castle, only: [:show, :edit, :update]

  # GET /castles
  # GET /castles.json
  def index
    @castles = Castle.all.order(:approved, :castle_name_en)
  end

  # GET /castles/1
  # GET /castles/1.json
  def show
    @castle = Castle.find(params[:id])
  end

  # GET /castles/new
  def new
    @castle = Castle.new
  end

  # GET /castles/1/edit
  def edit
  end

  # POST /castles
  # POST /castles.json
  def create
    @castle = Castle.new(castle_params)

    respond_to do |format|
      if @castle.save
        format.html { redirect_to @castle, notice: 'Castle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @castle }
      else
        format.html { render action: 'new' }
        format.json { render json: @castle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /castles/1
  # PATCH/PUT /castles/1.json
  def update
    respond_to do |format|
      if @castle.update(params)
        format.html { redirect_to @castle, notice: 'Castle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @castle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /castles/1
  # DELETE /castles/1.json
  def destroy
    @castle.destroy
    respond_to do |format|
      format.html { redirect_to castles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_castle
      @castle = Castle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def castle_params
      params[:castle]
    end
end

app/helpers/admin/castle_helper.rb
module Admin::CastleHelper
end

app/helpers/admin/castles_helper.rb
module Admin::CastlesHelper
end

app/helpers/castles_helper.rb
module CastlesHelper
end

app/views/admin/castles/_form.html.erb
<%= simple_form_for [:admin, @castle] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  <%= f.input :castle_name_en %>
  <%= f.input :castle_name_ja %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/castles/edit.html.erb
<h1>Editing castle</h1>

<%= render 'form' %>

<%= link_to 'Show', @castle %> |
<%= link_to 'Back', castles_path %>

app/views/admin/castles/index.html.erb
<h1>Listing castles</h1>

<table>
  <thead>
    <tr>
      <th>APP</th>
      <th>ID</th>
      <th>E Name</th>
      <th>J Name</th>
      <th>Pics</th>
      <th>value</th>
      <th>top100</th>
      <th>ICP</th>
      <th>NT</th>
      <th>Period</th>
      <th><i class="fi-eye"></i></th>
      <th><i class="fi-page-edit"></i></th>
      <th><i class="fi-trash"></i></th>
    </tr>
  </thead>

  <tbody>
    <% @castles.each do |castle| %>
      <tr class="<%= cycle('list-line-odd', 'list-line-even') %>">
        <td><%= castle.approved %></td>
        <td><%=h castle.id %></td>
        <td><%=h castle.castle_name_en %></td>
        <td><%=h castle.castle_name_ja %></td>
        <td> # </td>
        <td><%=h castle.historical_value %></td>
        <td><%=h castle.top_100 %></td>
        <td><%=h castle.has_ICP %></td>
        <td><%=h castle.has_NT %></td>
        <td><%=h castle.period %></td>
        <td><%= link_to admin_castle_path(castle) do %><i class="fi-eye"></i><% end %> </td>
        <td><%= link_to edit_admin_castle_path(castle) do %><i class="fi-page-edit"></i><% end %></td>
        <td><%= link_to castle, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fi-trash"> </i><% end %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Castle', new_castle_path %>

app/views/admin/castles/new.html.erb
<h1>New castle</h1>

<%= render 'form' %>

<%= link_to 'Back', castles_path %>

app/views/admin/castles/show.html.erb
<% if @castle.approved? %>APPROVED<% else %>NOT<% end %>

<table>
	<% for column in Castle.content_columns %>
		<tr>
			<td><b><%= column.name %>:</b></td><td><%= @castle.send(column.name) %></td>
		</tr>
	<% end %>
</table>
	